# compose.yml
services:
  manim-jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./notes:/notes
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser
    working_dir: /notes
